config/routes.rb
Rails.application.routes.draw do
  # Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Resources
  resources :games, only: %i[index show new create]
  resources :creators, only: %i[index show]
  Game::MANY_TAGS.each do |tag|
    resources tag.symbol_pluralized, only: %i[index show]
  end
  %i[platforms series engines developers modes].each do |object|
    resources object, only: %i[index show]
  end

  # Search
  get 'simple_search', to: 'search#simple'
  get 'search', to: 'search#new'
  get 'search_results', to: 'search#results'

  # Pages
  get 'tags', to: 'page#tags'

  # Home
  get 'home', to: 'page#home'
  root 'page#home'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    @search = TovgdbSearch.new(params)
  end
end

app/views/search/_game_tag.haml
.col-md-3.tags
  %h3{ class: game_tag.css_class }= game_tag.pluralized
  = collection_check_boxes(game_tag.lowercase_pluralized, :ids, game_tag.all, :id, :name) do |tag|
    = tag.label('data-value': tag.value) { tag.check_box + " #{tag.text}" }

app/views/search/new.html.haml
.search-form
  .row
    .col-md-12
      %h1 Advanced Search

  .row
    .col-md-12
      = form_tag(search_results_path, method: 'get') do
        .row
          .col-md-12
            = text_field_tag 'keywords', nil, class: 'keywords', placeholder: 'Enter Keywords'
            = submit_tag 'Search', class: 'search-button', id: 'first-search-button'

        .row.search-type
          .col-md-12
            = radio_button_tag 'match_type', 'all', true
            = label_tag 'match_type_all', 'Match ALL criteria'
            = radio_button_tag 'match_type', 'any'
            = label_tag 'match_type_any', 'Match ANY criteria'

        .row
          .col-md-3
            %h3.mode Modes
            = check_box_tag 'single_player'
            = label_tag 'single_player', 'Single Player'
            %br
            = check_box_tag 'multiplayer'
            = label_tag 'multiplayer', 'Multiplayer'
            %br
            = check_box_tag 'local_play'
            = label_tag 'local_play', 'Local Play'
            %br
            = check_box_tag 'online_play'
            = label_tag 'online_play', 'Online Play'
            %br
            = check_box_tag 'coop_play'
            = label_tag 'coop_play', 'Co-op Play'
            %br
            = check_box_tag 'competitive_play'
            = label_tag 'competitive_play', 'Competitive Play'

          - [Platform, Genre, Style].each do |game_tag|
            = render 'game_tag', game_tag: game_tag
        .row
          - [Theme, Engine, Community].each do |game_tag|
            = render 'game_tag', game_tag: game_tag

        .row
          .col-md-12
            = submit_tag 'Search', class: 'search-button pull-right', id: 'second-search-button'

app/views/search/results.html.haml
.row.standard-heading
  .col-md-12
    %h1 Search Results

.row.standard-summary
  .col-md-12
    %p
      Displaying <b>#{pluralize(@search.results.count, 'result')}</b> by matching <b>#{params[:match_type]}</b> of the following criteria:
      - if @search.criteria.present?
        %ul
          - if params[:keywords].present?
            %li Keywords: #{params[:keywords].split.join(', ')}
          - Game::TAGS.each do |tag_class|
            - tags = @search.criteria.select { |criteria| criteria[:category] == tag_class.symbol_pluralized }
            - if tags.present?
              %li #{tag_class.pluralized}: #{tags.map { |word| "<b>#{word[:criteria]}</b>" }.join(', ').html_safe}
      - else
        %ul
          %li
            %em No criteria provided
      %hr

  .col-md-12.standard-list
    - if @search.results.present?
      - @search.results.each do |result|
        :ruby
          game           = result[:game]
          elastic_search = result[:elastic_search]
          criteria       = result[:criteria]
        .row.standard-list-item
          .game-img.col-sm-3.col-xs-5.col-xxs-12
            = image_tag game.game_images.first.image.url(:small) if game.game_images?
          .search-results.game-details.col-sm-9.col-xs-7.col-xxs-12
            %h2= link_to_by_name game
            -# TODO: make `game.published_developers` work instead of `game.developers(&:published)` using eager loading
            %h3= link_to_by_names game.developers(&:published)
            %p
              - if elastic_search && elastic_search.highlight.long_description.present?
                = elastic_search.highlight.long_description.join.html_safe
              - else
                = game.shortened_description

            - if params[:match_type] == 'any'
              .game-tags
                - Game::TAGS.each do |tag_class|
                  - criteria.select { |criterion| criterion[:category] == tag_class.symbol_pluralized }.each do |tag_criteria|
                    - tag = tag_class.find_by_name(tag_criteria[:criteria])
                    = link_to_by_name tag, class: tag_class.css_class

    - else
      %p
        %b No Results

  .col-md-12
    %hr
    %p= link_to 'Advanced Search Options', search_path

= render 'shared/explore_tags'